title: Web Greeter
description: A modern, visually appealing greeter for LightDM.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-mentions
  - jekyll-coffeescript
  - jekyll-paginate
